### ISSUE TITLE
Feature request: String output of Chart

### ISSUE THREAD

**Issue by paulirotta** [loony-bean/textplots-rs#29]
`Chart::display()` output directly with `println!()`

It would be nice to be able to return a String. That allows for example to transfer over a network or include a log file.

It seems relatively staightforward to use `format!()` instead and allow this additional method. The issue might be more a consistent API pattern (`display()` vs `display_string() etc`) across the library for similiar situations.

**Comment by loony-bean** [comment]
Fixed in #35
