### ISSUE TITLE
Further Plot Customization—Hide Axis

### ISSUE THREAD

**Issue by milespossing** [loony-bean/textplots-rs#39]
Hello, I've poked around a little bit, but can tend to miss stuff, so sorry if I have.

I'm looking to plot without the axis at all. I don't mind attempting to contribute to add this feature myself, but I wanted to check here first. Here is what my plots are looking like:

![image](https://user-images.githubusercontent.com/7330275/204435843-80929a6c-4463-4fc2-8ffd-018820d36c0b.png)

I would like both the axis, as well as the axis labels to be omitted. Is this possible? And if not, would it be desirable to add in to this library?

**Comment by uandere** [comment]
Working on that

**Comment by loony-bean** [comment]
Hey @milespossing! [This](https://github.com/loony-bean/textplots-rs/blob/master/src/lib.rs#L130) has been added recently. It will be cool to hear what you think.

**Comment by milespossing** [comment]
Yes this worked like a charm. Thanks so much!
